import { afterEach, describe, expect, test } from "bun:test";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  checkKit,
  generateKit,
  getKitVersion,
  KIT_MANIFEST_FILE,
  KIT_TARGET_SUBDIR,
  KIT_TEMPLATE_FILES,
  renderKit,
  type KitManifest,
} from "../src/kit/generate";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const tmpDirs: string[] = [];

function makeTarget(withContract = true): string {
  const dir = mkdtempSync(join(tmpdir(), "kit-gen-"));
  tmpDirs.push(dir);
  if (withContract) {
    writeFileSync(
      join(dir, "hasna.contract.json"),
      JSON.stringify(
        { schema: "hasna.service_contract.v1", name: "demo", class: "cli-with-store", contractVersion: "v1", kitVersion: "0.0.0" },
        null,
        2,
      ),
    );
  }
  return dir;
}

afterEach(() => {
  while (tmpDirs.length) {
    const dir = tmpDirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

describe("storage-kit generator", () => {
  test("stamps all files with header + version and updates the contract", () => {
    const dir = makeTarget();
    const result = generateKit({ targetRepo: dir });
    const kitDir = join(dir, KIT_TARGET_SUBDIR);

    for (const file of KIT_TEMPLATE_FILES) {
      expect(existsSync(join(kitDir, file))).toBe(true);
    }
    const mode = readFileSync(join(kitDir, "mode.ts"), "utf8");
    expect(mode).toContain("@generated by @hasna/contracts vendor-kit");
    expect(mode).toContain(`KIT_VERSION: ${result.version}`);

    const index = readFileSync(join(kitDir, "index.ts"), "utf8");
    expect(index).toContain(`export const KIT_VERSION = "${result.version}"`);
    expect(index).not.toContain("__KIT_VERSION__");

    const manifest = JSON.parse(readFileSync(join(kitDir, KIT_MANIFEST_FILE), "utf8")) as KitManifest;
    expect(manifest.kitVersion).toBe(result.version);
    expect(Object.keys(manifest.files).sort()).toEqual([...KIT_TEMPLATE_FILES].sort());

    const contract = JSON.parse(readFileSync(join(dir, "hasna.contract.json"), "utf8"));
    expect(contract.kitVersion).toBe(result.version);
    expect(result.contractUpdated).toBe(true);
  });

  test("--no-contract leaves hasna.contract.json untouched", () => {
    const dir = makeTarget();
    const result = generateKit({ targetRepo: dir, writeContract: false });
    expect(result.contractUpdated).toBe(false);
    const contract = JSON.parse(readFileSync(join(dir, "hasna.contract.json"), "utf8"));
    expect(contract.kitVersion).toBe("0.0.0");
  });

  test("check passes on a fresh vendor and fails on hand-edit / missing / extra", () => {
    const dir = makeTarget();
    generateKit({ targetRepo: dir });
    expect(checkKit({ targetRepo: dir }).ok).toBe(true);

    // hand-edit
    const kitDir = join(dir, KIT_TARGET_SUBDIR);
    writeFileSync(join(kitDir, "mode.ts"), readFileSync(join(kitDir, "mode.ts"), "utf8") + "\n// tampered\n");
    const edited = checkKit({ targetRepo: dir });
    expect(edited.ok).toBe(false);
    expect(edited.files.find((f) => f.file === "mode.ts")?.status).toBe("modified");

    // extra file
    generateKit({ targetRepo: dir });
    writeFileSync(join(kitDir, "rogue.ts"), "export const x = 1;\n");
    const withExtra = checkKit({ targetRepo: dir });
    expect(withExtra.ok).toBe(false);
    expect(withExtra.extras).toContain("rogue.ts");

    // missing file
    rmSync(join(kitDir, "rogue.ts"));
    rmSync(join(kitDir, "tls.ts"));
    const missing = checkKit({ targetRepo: dir });
    expect(missing.files.find((f) => f.file === "tls.ts")?.status).toBe("missing");
  });

  test("check reports stale version when installed version differs", () => {
    const dir = makeTarget();
    generateKit({ targetRepo: dir, version: "9.9.9" });
    const result = checkKit({ targetRepo: dir, version: getKitVersion() });
    expect(result.ok).toBe(false);
    expect(result.staleVersion).toBe("9.9.9");
  });

  test("render is deterministic for a version", () => {
    const a = renderKit("1.2.3");
    const b = renderKit("1.2.3");
    expect(a.manifest.files).toEqual(b.manifest.files);
  });

  test("generated kit typechecks standalone (strict, Bundler resolution)", () => {
    const dir = makeTarget(false);
    generateKit({ targetRepo: dir, writeContract: false });
    // Point at the package's node_modules so pg + node types resolve.
    symlinkSync(join(REPO_ROOT, "node_modules"), join(dir, "node_modules"), "dir");
    writeFileSync(
      join(dir, "tsconfig.json"),
      JSON.stringify({
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "Bundler",
          types: ["node"],
          strict: true,
          noUncheckedIndexedAccess: true,
          exactOptionalPropertyTypes: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: [`${KIT_TARGET_SUBDIR}/**/*.ts`],
      }),
    );
    // Throws (non-zero exit) if the generated output does not typecheck.
    execFileSync("bunx", ["tsc", "--noEmit", "-p", "tsconfig.json"], { cwd: dir, stdio: "pipe" });
  }, 60_000);
});
