// Public surface of the vendored Hasna storage kit.
//
// This is a canonical PostgreSQL server storage kit generated by
// `@hasna/contracts`. Clients never import it or open PostgreSQL directly.
//
// Do not hand-edit files in this directory — CI verifies them against the
// generator with `contracts vendor-kit --check`. Regenerate with
// `bunx @hasna/contracts vendor-kit`.

export const KIT_VERSION = "__KIT_VERSION__";

export * from "./backend.js";
export * from "./tls.js";
export * from "./query.js";
export * from "./pool.js";
export * from "./migrations.js";
export * from "./health.js";
