// Public surface of the vendored Hasna storage kit.
//
// This is a canonical Postgres storage kit generated by `@hasna/contracts`.
// It is PURE REMOTE per Amendment A1: cloud mode reads AND writes go directly
// to cloud Postgres. There is NO sync engine, NO cache-as-mode, and NO merge
// logic anywhere in this kit.
//
// Do not hand-edit files in this directory — CI verifies them against the
// generator with `contracts vendor-kit --check`. Regenerate with
// `bunx @hasna/contracts vendor-kit`.

export const KIT_VERSION = "__KIT_VERSION__";

export * from "./mode.js";
export * from "./tls.js";
export * from "./query.js";
export * from "./pool.js";
export * from "./migrations.js";
export * from "./health.js";
