export interface TodosRuntimeValidatorBinding {
  id: string;
  sourceFile: string;
  symbol: string;
  kind: "refinement" | "validator" | "schema";
  invariantIds: readonly string[];
  schemaIds: readonly string[];
}

const PAGE_SCHEMA_IDS = [
  "hasna.todos.response.capability_page.v1",
  "hasna.todos.response.task_page.v1",
  "hasna.todos.response.activity_page.v1",
  "hasna.todos.response.comment_page.v1",
  "hasna.todos.response.dependency_page.v1",
  "hasna.todos.response.project_page.v1",
  "hasna.todos.response.task_list_page.v1",
  "hasna.todos.response.plan_page.v1",
  "hasna.todos.response.agent_page.v1",
  "hasna.todos.response.saved_view_page.v1",
  "hasna.todos.response.verification_page.v1",
  "hasna.todos.response.task_file_page.v1",
  "hasna.todos.response.run_page.v1",
  "hasna.todos.response.run_event_page.v1",
  "hasna.todos.response.run_command_page.v1",
  "hasna.todos.response.run_file_page.v1",
  "hasna.todos.response.run_artifact_page.v1",
  "hasna.todos.response.git_commit_page.v1",
  "hasna.todos.response.git_ref_page.v1",
  "hasna.todos.response.projection_page.v1",
  "hasna.todos.response.migration_receipt_page.v1",
  "hasna.todos.response.deletion_record_page.v1",
  "hasna.todos.response.approval_page.v1",
  "hasna.todos.response.task_template_page.v1",
] as const;

function binding(value: TodosRuntimeValidatorBinding): TodosRuntimeValidatorBinding {
  return Object.freeze(value);
}

/**
 * Independent mechanical inventory for every custom refinement and exported
 * semantic validator. Invariant declarations do not derive from this list.
 */
export const TODOS_RUNTIME_VALIDATOR_BINDINGS =
  Object.freeze<TodosRuntimeValidatorBinding[]>([
    binding({
      id: "common.relative_path_semantics",
      sourceFile: "common.ts",
      symbol: "TodosRelativePathSchema",
      kind: "refinement",
      invariantIds: ["todos.common.relative_path"],
      schemaIds: [
        "hasna.todos.task_file.v1",
        "hasna.todos.run_file.v1",
        "hasna.todos.git_commit.v1",
        "hasna.todos.request.task_file_record.v1",
        "hasna.todos.request.run_file_create.v1",
        "hasna.todos.request.git_commit_link.v1",
      ],
    }),
    binding({
      id: "identity.context_semantics",
      sourceFile: "identity.ts",
      symbol: "TodosIdentityContextSchema",
      kind: "refinement",
      invariantIds: ["todos.identity.context_semantics"],
      schemaIds: ["hasna.todos.identity_context.v1"],
    }),
    binding({
      id: "identity.authorization_binding",
      sourceFile: "identity.ts",
      symbol: "validateTodosIdentityContext",
      kind: "validator",
      invariantIds: ["todos.identity.authorization_binding"],
      schemaIds: ["hasna.todos.identity_context.v1"],
    }),
    binding({
      id: "authority.config_semantics",
      sourceFile: "authority.ts",
      symbol: "TodosAuthorityConfigSchema",
      kind: "refinement",
      invariantIds: [
        "todos.authority.mode_binding",
        "todos.authority.capability_uniqueness",
      ],
      schemaIds: ["hasna.todos.authority_config.v1"],
    }),
    binding({
      id: "authority.handshake_semantics",
      sourceFile: "authority.ts",
      symbol: "TodosAuthorityHandshakeSchema",
      kind: "refinement",
      invariantIds: [
        "todos.authority.mode_binding",
        "todos.authority.capability_uniqueness",
      ],
      schemaIds: ["hasna.todos.authority_handshake.v1"],
    }),
    binding({
      id: "authority.canonical_binding",
      sourceFile: "canonical-authority.ts",
      symbol: "TodosCanonicalAuthorityHandshakeSchema",
      kind: "refinement",
      invariantIds: ["todos.authority.canonical_binding"],
      schemaIds: ["hasna.todos.authority_handshake.v1"],
    }),
    binding({
      id: "authority.validate_canonical_handshake",
      sourceFile: "canonical-authority.ts",
      symbol: "validateCanonicalTodosAuthorityHandshake",
      kind: "validator",
      invariantIds: ["todos.authority.canonical_binding"],
      schemaIds: ["hasna.todos.authority_handshake.v1"],
    }),
    binding({
      id: "domain.task_record_semantics",
      sourceFile: "domain.ts",
      symbol: "TodosTaskSchema",
      kind: "refinement",
      invariantIds: ["todos.domain.task_record"],
      schemaIds: ["hasna.todos.task.v1"],
    }),
    binding({
      id: "domain.task_status_transition",
      sourceFile: "domain.ts",
      symbol: "validateTodosTaskStatusTransition",
      kind: "validator",
      invariantIds: ["todos.domain.task_status_transition"],
      schemaIds: ["hasna.todos.task.v1"],
    }),
    binding({
      id: "domain.agent_role_uniqueness",
      sourceFile: "domain.ts",
      symbol: "TodosAgentSchema",
      kind: "refinement",
      invariantIds: ["todos.domain.agent_role_uniqueness"],
      schemaIds: ["hasna.todos.agent.v1"],
    }),
    binding({
      id: "domain.dependency_self_reference",
      sourceFile: "domain.ts",
      symbol: "TodosDependencySchema",
      kind: "refinement",
      invariantIds: ["todos.domain.dependency_self_reference"],
      schemaIds: ["hasna.todos.dependency.v1"],
    }),
    binding({
      id: "domain.git_object_id",
      sourceFile: "domain.ts",
      symbol: "TodosGitObjectIdSchema",
      kind: "refinement",
      invariantIds: ["todos.domain.git_object_id"],
      schemaIds: ["hasna.todos.git_object_id.v1"],
    }),
    binding({
      id: "response.page_count",
      sourceFile: "errors.ts",
      symbol: "createTodosPageSchema",
      kind: "refinement",
      invariantIds: ["todos.response.page_count"],
      schemaIds: PAGE_SCHEMA_IDS,
    }),
    binding({
      id: "operation.manifest_semantics",
      sourceFile: "operations.ts",
      symbol: "TodosOperationManifestSchema",
      kind: "refinement",
      invariantIds: ["todos.operation.manifest_semantics"],
      schemaIds: ["hasna.todos.operation_manifest.v1"],
    }),
    binding({
      id: "operation.task_update_nonempty",
      sourceFile: "operation-schemas.ts",
      symbol: "TaskUpdateRequestSchema",
      kind: "refinement",
      invariantIds: ["todos.operation.task_update_nonempty"],
      schemaIds: ["hasna.todos.request.task_update.v1"],
    }),
    binding({
      id: "operation.transfer_checkpoint_binding",
      sourceFile: "operation-schemas.ts",
      symbol: "TransferImportExecuteRequestSchema",
      kind: "refinement",
      invariantIds: ["todos.operation.transfer_checkpoint_binding"],
      schemaIds: ["hasna.todos.request.transfer_import_execute.v1"],
    }),
    binding({
      id: "operation.public_transfer_import_execute_canonical",
      sourceFile: "public-operation-schemas.ts",
      symbol: "PublicTransferImportExecuteRequestSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.public_canonical_boundaries"],
      schemaIds: ["hasna.todos.request.transfer_import_execute.v1"],
    }),
    binding({
      id: "invocation.operation_binding",
      sourceFile: "invocation.ts",
      symbol: "TodosOperationInvocationSchema",
      kind: "refinement",
      invariantIds: [
        "todos.invocation.canonical_digests",
        "todos.invocation.authority_identity_binding",
        "todos.invocation.operation_mode_scope_request",
      ],
      schemaIds: ["hasna.todos.operation_invocation.v1"],
    }),
    binding({
      id: "invocation.validate_operation",
      sourceFile: "invocation.ts",
      symbol: "validateTodosOperationInvocation",
      kind: "validator",
      invariantIds: [
        "todos.invocation.canonical_digests",
        "todos.invocation.authority_identity_binding",
        "todos.invocation.operation_mode_scope_request",
      ],
      schemaIds: ["hasna.todos.operation_invocation.v1"],
    }),
    binding({
      id: "contract.verify_digest_closure",
      sourceFile: "contract.ts",
      symbol: "verifyTodosContractDigests",
      kind: "validator",
      invariantIds: ["todos.contract.digest_closure"],
      schemaIds: ["hasna.todos.contract.v1"],
    }),
    binding({
      id: "contract.digest_closure",
      sourceFile: "contract.ts",
      symbol: "validateTodosContractDescriptor",
      kind: "validator",
      invariantIds: ["todos.contract.digest_closure"],
      schemaIds: ["hasna.todos.contract.v1"],
    }),
    binding({
      id: "transfer.bundle_owner_binding",
      sourceFile: "transfer-schema.ts",
      symbol: "TodosTransferBundleSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.source_authority"],
      schemaIds: ["hasna.todos.transfer_bundle.v1"],
    }),
    binding({
      id: "transfer.integrity",
      sourceFile: "transfer-schema.ts",
      symbol: "validateTodosTransferBundleIntegrity",
      kind: "validator",
      invariantIds: [
        "todos.transfer.section_integrity",
        "todos.transfer.classification",
        "todos.transfer.reference_closure",
        "todos.transfer.dependency_closure",
        "todos.transfer.attachment_content_addressing",
        "todos.transfer.deletion_redaction",
      ],
      schemaIds: ["hasna.todos.transfer_bundle.v1"],
    }),
    binding({
      id: "transfer.canonical_digests",
      sourceFile: "transfer.ts",
      symbol: "validateTodosTransferBundle",
      kind: "validator",
      invariantIds: ["todos.transfer.canonical_digests"],
      schemaIds: ["hasna.todos.transfer_bundle.v1"],
    }),
    binding({
      id: "transfer.public_checkpoint_canonical",
      sourceFile: "transfer.ts",
      symbol: "TodosTransferCheckpointSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.public_canonical_boundaries"],
      schemaIds: ["hasna.todos.transfer_checkpoint.v1"],
    }),
    binding({
      id: "transfer.public_receipt_canonical",
      sourceFile: "transfer.ts",
      symbol: "TodosMigrationReceiptSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.public_canonical_boundaries"],
      schemaIds: [
        "hasna.todos.migration_receipt.v1",
        "hasna.todos.response.migration_receipt.v1",
        "hasna.todos.response.migration_receipt_page.v1",
      ],
    }),
    binding({
      id: "transfer.public_execution_request_canonical",
      sourceFile: "transfer.ts",
      symbol: "TodosTransferImportExecutionSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.public_canonical_boundaries"],
      schemaIds: ["hasna.todos.transfer_import_execution.v1"],
    }),
    binding({
      id: "transfer.public_checkpoint_transition",
      sourceFile: "transfer.ts",
      symbol: "validateTodosTransferCheckpointTransition",
      kind: "validator",
      invariantIds: ["todos.transfer.public_canonical_boundaries"],
      schemaIds: ["hasna.todos.transfer_checkpoint.v1"],
    }),
    binding({
      id: "transfer.public_receipt_chain",
      sourceFile: "transfer.ts",
      symbol: "validateTodosMigrationReceiptChain",
      kind: "validator",
      invariantIds: [
        "todos.transfer.public_canonical_boundaries",
        "todos.transfer.receipt_chain",
      ],
      schemaIds: ["hasna.todos.migration_receipt.v1"],
    }),
    binding({
      id: "transfer.import_plan_digest",
      sourceFile: "transfer-schema.ts",
      symbol: "TodosTransferImportPreviewSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.import_plan"],
      schemaIds: ["hasna.todos.transfer_import_preview.v1"],
    }),
    binding({
      id: "transfer.checkpoint_record",
      sourceFile: "transfer-schema.ts",
      symbol: "TodosTransferCheckpointSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.checkpoint_binding"],
      schemaIds: ["hasna.todos.transfer_checkpoint.v1"],
    }),
    binding({
      id: "transfer.checkpoint_transition",
      sourceFile: "transfer-schema.ts",
      symbol: "validateTodosTransferCheckpointTransition",
      kind: "validator",
      invariantIds: ["todos.transfer.checkpoint_monotonicity"],
      schemaIds: ["hasna.todos.transfer_checkpoint.v1"],
    }),
    binding({
      id: "transfer.execution_request",
      sourceFile: "transfer-schema.ts",
      symbol: "TodosTransferImportExecutionSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.execution_request_binding"],
      schemaIds: ["hasna.todos.transfer_import_execution.v1"],
    }),
    binding({
      id: "transfer.execution_context",
      sourceFile: "transfer-schema.ts",
      symbol: "TodosTransferExecutionContextSchema",
      kind: "schema",
      invariantIds: ["todos.transfer.execution_context_closed"],
      schemaIds: ["hasna.todos.transfer_execution_context.v1"],
    }),
    binding({
      id: "transfer.receipt_record",
      sourceFile: "transfer-schema.ts",
      symbol: "TodosMigrationReceiptSchema",
      kind: "refinement",
      invariantIds: ["todos.transfer.receipt_binding"],
      schemaIds: ["hasna.todos.migration_receipt.v1"],
    }),
    binding({
      id: "transfer.receipt_chain",
      sourceFile: "transfer-schema.ts",
      symbol: "validateTodosMigrationReceiptChain",
      kind: "validator",
      invariantIds: ["todos.transfer.receipt_chain"],
      schemaIds: ["hasna.todos.migration_receipt.v1"],
    }),
    binding({
      id: "transfer.execution_replay",
      sourceFile: "transfer-schema.ts",
      symbol: "evaluateTodosImportExecutionIntegrity",
      kind: "validator",
      invariantIds: ["todos.transfer.replay_binding"],
      schemaIds: [
        "hasna.todos.transfer_import_execution.v1",
        "hasna.todos.transfer_execution_context.v1",
      ],
    }),
    binding({
      id: "transfer.canonical_execution",
      sourceFile: "transfer.ts",
      symbol: "evaluateTodosImportExecution",
      kind: "validator",
      invariantIds: ["todos.transfer.execution_canonical_digests"],
      schemaIds: ["hasna.todos.transfer_import_execution.v1"],
    }),
    binding({
      id: "projection.head_binding",
      sourceFile: "projection.ts",
      symbol: "TaskToPrHeadBindingSchema",
      kind: "refinement",
      invariantIds: ["todos.projection.exact_head"],
      schemaIds: ["hasna.todos.task_to_pr_projection.v1"],
    }),
    binding({
      id: "projection.record_binding",
      sourceFile: "projection.ts",
      symbol: "TaskToPrProjectionSchema",
      kind: "refinement",
      invariantIds: [
        "todos.projection.opaque_refs",
        "todos.projection.owner_kind_binding",
        "todos.projection.proof_identity",
        "todos.projection.digest_predecessor",
      ],
      schemaIds: ["hasna.todos.task_to_pr_projection.v1"],
    }),
    binding({
      id: "projection.transition",
      sourceFile: "projection.ts",
      symbol: "validateTaskToPrProjectionTransition",
      kind: "validator",
      invariantIds: ["todos.projection.digest_predecessor"],
      schemaIds: ["hasna.todos.task_to_pr_projection.v1"],
    }),
    binding({
      id: "projection.history",
      sourceFile: "projection.ts",
      symbol: "validateTaskToPrProjectionHistory",
      kind: "validator",
      invariantIds: ["todos.projection.full_history"],
      schemaIds: ["hasna.todos.task_to_pr_projection.v1"],
    }),
    binding({
      id: "artifacts.canonical_bytes",
      sourceFile: "artifacts.ts",
      symbol: "verifyTodosRenderedArtifacts",
      kind: "validator",
      invariantIds: ["todos.artifacts.canonical_bytes"],
      schemaIds: ["hasna.todos.contract.v1"],
    }),
  ]);
